const listProduct = [
    {id:1,name:'Iphone 15 Promax',price:'1500',img:(require('../assets/iphone15prm.png')),title:'Smart Phone',sale:'Best Seller'},
    {id:2,name:'Iphone 16 Promax',price:'1600',img:(require('../assets/iphone15prm.png')),title:'Smart Phone',sale:'Best Matched'},
    {id:3,name:'Iphone 17 Promax',price:'1700',img:(require('../assets/iphone15prm.png')),title:'Smart Phone',sale:'Popular'},
    {id:4,name:'Iphone 15 Promax',price:'1500',img:(require('../assets/iphone15prm.png')),title:'Smart Phone',sale:'Best Seller'},
    {id:5,name:'Iphone 16 Promax',price:'1600',img:(require('../assets/iphone15prm.png')),title:'Smart Phone',sale:'Best Matched'},
    {id:6,name:'Iphone 17 Promax',price:'1700',img:(require('../assets/iphone15prm.png')),title:'Smart Phone',sale:'Popular'},
    {id:7,name:'MacBook Pro 24in',price:'1500',img:(require('../assets/macbook.png')),title:'MacBook',sale:'Best Seller'},
    {id:8,name:'MacBook Pro 22in',price:'1500',img:(require('../assets/macbook.png')),title:'MacBook',sale:'Best Matched'},
    {id:9,name:'MacBook Pro 20in',price:'1500',img:(require('../assets/macbook.png')),title:'MacBook',sale:'Popular'},
    {id:10,name:'MacBook Pro 24in',price:'1500',img:(require('../assets/macbook.png')),title:'MacBook',sale:'Best Seller'},
    {id:11,name:'MacBook Pro 22in',price:'1500',img:(require('../assets/macbook.png')),title:'MacBook',sale:'Best Matched'},
    {id:12,name:'MacBook Pro 20in',price:'1500',img:(require('../assets/macbook.png')),title:'MacBook',sale:'Popular'},
    {id:13,name:'Ipad Pro',price:'1500',img:(require('../assets/macbook.png')),title:'Ipad',sale:'Best Seller'},
    {id:14,name:'Ipad Cùi',price:'1500',img:(require('../assets/macbook.png')),title:'Ipad',sale:'Best Matched'},
    {id:15,name:'Ipad lỏ',price:'1500',img:(require('../assets/macbook.png')),title:'Ipad',sale:'Popular'},
    {id:16,name:'Ipad dởm',price:'1500',img:(require('../assets/macbook.png')),title:'Ipad',sale:'Best Seller'},
    {id:17,name:'Ipad sida',price:'1500',img:(require('../assets/macbook.png')),title:'Ipad',sale:'Best Matched'},
    {id:18,name:'Ipad Vip',price:'1500',img:(require('../assets/macbook.png')),title:'Ipad',sale:'Popular'},
]